# Generated by Django 4.0.2 on 2022-02-07 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Department', '0002_department_dept_id_students_std_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
